package controllers.api

import play.api.Play

/**
 * Created by Administrator on 2015-09-10.
 */
object StaticValues {
  val API_SECRET = Some("sQzVKrZqrVYOt/KaAlsw5Adu2es")
  val USER_TYPE_ADMIN = 1
  val USER_TYPE_STUDENT = 2
  val USER_TYPE_TEACHER = 3
  val USER_TYPE_MENTOR = 4
  val USER_TYPE = List("", "관리자", "학생", "선생님", "멘토")
  val FILE_UPLOAD_BASE_PATH = "C:/upload/"
  val POSTING_IMAGE_UPLOAD_PATH = "postings/"
  val REPLY_IMAGE_UPLOAD_PATH = "replies/"
  val PROFILE_IMAGE_UPLOAD_PATH = "profiles/"
  val MENTORING_TYPE_ID = 10
  val CLINIC_TYPE_ID = 20
  val SUBJECT_ID_KOREAN = 10000
  val SUBJECT_ID_MATH_A = 30000
  val SUBJECT_ID_MATH_B = 20000
  val SUBJECT_ID_ENGLISH = 50000
  val EXAM_RECORD_TYPE_GRADE = 1
  val EXAM_RECORD_TYPE_SCORE = 2
  val EXAM_RECORD_TYPE_PERCENTILE = 3
  val EXAM_RECORD_TYPE_STANDARD = 4
  val ACTIVITY_TYPE_STUDY = 1
  val ACTIVITY_TYPE_ACTIVITY = 2
  val ACTIVITY_TYPE_CUSTOM = 3
  val ACTIVITY_STUDY_TYPE_KOREA = 1
  val ACTIVITY_STUDY_TYPE_MATH = 2
  val ACTIVITY_STUDY_TYPE_ENGLISH = 3
  val ACTIVITY_STUDY_TYPE_SCIENCE = 4
  val ACTIVITY_STUDY_TYPE_SOCIAL = 5

  val ACTIVITY_SUB_TYPE_EXERCISE = 8
  val ACTIVITY_SUB_TYPE_READING = 9
  val ACTIVITY_SUB_TYPE_EAT = 10
  val ACTIVITY_SUB_TYPE_SLEEP = 11
  val ACTIVITY_SUB_TYPE_LEISURE = 12
  val ACTIVITY_SUB_TYPE_REST = 13

  val ACTIVITY_TYPE_INDEPENDENTLY = 1
  val ACTIVITY_TYPE_LECTURE = 2
  val ACTIVITY_TYPE_SCHOOL = 3
  val ACTIVITY_TYPE_PRIVATE_EDU = 4
  val ACTIVITY_TYPE_PRIVATE_TEACHER = 5
  val ACTIVITY_TYPE_CHECK = 6
  val ACTIVITY_TYPE_EXAM = 7

  val ANALYSIS_CATEGORY_BASIC = 100
  val ANALYSIS_CATEGORY_SOLUTION = 200
  val ANALYSIS_CATEGORY_EBS = 300
  val ANALYSIS_CATEGORY_REAL = 400

  val ANSWER_POINT = 200
}
