package controllers.admin

/**
 * Created by Administrator on 2015-09-10.
 */
object Properties {
  val API_SECRET = Some("sQzVKrZqrVYOt/KaAlsw5Adu2es")
  val USER_TYPE_ADMIN = 1
  val USER_TYPE_STUDENT = 2
  val USER_TYPE_TEACHER = 3
  val USER_TYPE_MENTOR = 4
  val USER_TYPE = List("", "관리자", "학생", "선생님", "멘토")

  val PAGE_SIZE = 10
  val ADMIN_ID = 1

  val PUSH_CODE_STUDENT = "201"
  val PUSH_CODE_MENTOR_CLINIC = "401"
  val PUSH_CODE_MENTOR_POINT = "402"
  val PUSH_CODE_MENTOR_ANSWER = "403"
  val PUSH_CODE_MENTOR_MANUAL = "404"

  val PUSH_MESSAGE_ID_STUDENT_LESS = 1
  val PUSH_MESSAGE_ID_STUDENT_MORE = 2
  val PUSH_MESSAGE_ID_STUDENT_CLINIC_REPLY = 3
  val PUSH_MESSAGE_ID_STUDENT_MENTORING_REPLY = 4
  val PUSH_MESSAGE_ID_STUDENT_REPORT = 5
  val PUSH_MESSAGE_ID_STUDENT_EXAM = 6
  val PUSH_MESSAGE_ID_STUDENT_CHOICE = 7
  val PUSH_MESSAGE_ID_MENTOR_CLINIC_QUESTION = 8
  val PUSH_MESSAGE_ID_MENTOR_CLINIC_EVALUATION = 9
  val PUSH_MESSAGE_ID_MENTOR_MENTORING_REPLY = 10
  val PUSH_MESSAGE_ID_MENTOR_MENTORING_EVALUATION = 11
  val PUSH_MESSAGE_ID_MENTOR_REPORT = 12
  val PUSH_MESSAGE_ID_MENTOR_CHOICE_CANCEL = 13
  val PUSH_MESSAGE_ID_MENTOR_REFUND = 14
}
